In [11]:
import numpy as np
A = np.array([[56,0,4.4,68],[1.2,104,52,8],[1.8,35,99,.9]])
print(A)
cal = A.sum(axis=0)
print(cal)
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8   35.    99.     0.9]]
[  59.   139.   155.4   76.9]
[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  74.82014388  33.46203346  10.40312094]
 [  3.05084746  25.17985612  63.70656371   1.17035111]]


In [6]:
import time
a= np.random.rand(1000000)
b= np.random.rand(1000000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print("Vectorized version: " + str(1000* (toc-tic)) + " ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(" Non Vectorized version: " + str(1000* (toc-tic)) + " ms")

Vectorized version: 1.1382102966308594 ms
 Non Vectorized version: 428.3490180969238 ms


In [15]:
import numpy as np

# don't do
a = np.random.rand(5)

# do
b = np.random.rand(5,1)

print(a, a.shape)
print(b, b.shape)

# a.shape = (5,1): column vector
# a.shape = (1,5): row vector
# use: assert(a.shape == (1,5))

[ 0.48826523  0.40703568  0.16339736  0.207719    0.16277862] (5,)
[[ 0.66484075]
 [ 0.41109909]
 [ 0.32487389]
 [ 0.0673594 ]
 [ 0.46766001]] (5, 1)


In [16]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c.shape)

(2, 3)


In [17]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [18]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [29]:
# a.shape = (3,4)
# b.shape = (4,1)

q = np.random.rand(3,4)
r = np.random.rand(4,1)
d = q + r.T
# for i in range(3):
#   for j in range(4):
#     d[i][j] = q[i][j] + r[j]
    
print(d.shape)

(3, 4)


In [33]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(a)
print(b)
print(c)

[[-0.4943467  -0.9847153   0.44999463]
 [-0.95271629  1.99914465  1.30510636]
 [-0.768363   -0.73199227 -0.59642805]]
[[-0.06910625]
 [ 0.17175747]
 [ 0.50536828]]
[[ 0.03416245  0.06804998 -0.03109744]
 [-0.16363614  0.34336803  0.22416177]
 [-0.38830629 -0.36992568 -0.30141582]]
